<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zytxt.PrintClient.Core\Zytxt.PrintClient.Core.csproj" />
    <ProjectReference Include="..\..\src\Zytxt.PrintClient.Host\Zytxt.PrintClient.Host.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
